
use_frameworks!

target 'Book_Example' do
  # pod 'Book', :path => '../'
  # pod 'Book', :podspec => '../'
  pod 'Book', :git => 'https://github.com/srv7/Book.git'
  
  
end

target 'Book_Example_swift' do
  # pod 'Book', :path => '../'
  # pod 'Book', :podspec => '../'
  pod 'Book', :git => 'https://github.com/srv7/Book.git'
  
  
end
